name: Deploy to AWS MAIN ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Docker Image to AWS ECR MAIN
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2
      AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t my-docker-image .
          docker tag my-docker-image:latest ${{ secrets.AWS_ECR_REGISTRY }}/my-docker-image:latest
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/
